---
title: "p8105_hw2_yk2960"
author: "Youyuan(Keviant) Kong"
date: "2021/10/1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(haven)
library(readxl)
library(dplyr)
library(ggplot2)

```
## Problem 1
### Mr.Trash_Wheel

```{r Mr.Trash_Wheel}
Mr.Trash_Wheel<-read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx"
                           ,range="A2:N408",sheet="Mr. Trash Wheel") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls=round(sports_balls))
```
### Report for Mr.Trash_Wheel
```{r report 1}
cat("there are ",nrow(Mr.Trash_Wheel),"obeservations in the Mr.Trash Wheel dataset,and the main variable names are:
",
colnames(Mr.Trash_Wheel)
)
cat("the median number of sports balls in a dumpster in 2017 is ",
    filter(Mr.Trash_Wheel,year==2017) %>% 
      pull(sports_balls) %>% 
      median()
)

#### need other reports

```

### precipitation data for 2018 and 2019
```{r precipitation data for 2018 and 2019}
precipitation_2018<-read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx"
                           ,sheet="2018 Precipitation",range="A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year=2018,month=month.name)
  
precipitation_2019<-read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx"
                           ,sheet="2019 Precipitation",range="A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year=2019,month=month.name)
precipitation_2018_2019<-bind_rows(precipitation_2018,precipitation_2019)

##precipitation_2018_2019<-bind_rows(pivot_wider(precipitation_2018,
##                                     names_from=month,
##                                     values_from="total"),
##                                   pivot_wider(precipitation_2019,
##                                     names_from=month,
##                                     values_from="total")
##)

```
### Report for Precipitation Data for 2018 and 2019
```{r report 2}
cat("there are ",nrow(precipitation_2018_2019),
"obeservations in the Mr.Trash Wheel dataset,and the main variable names are:
",
colnames(precipitation_2018_2019)
)
cat("the total precipitation in 2018 is",
    filter(precipitation_2018_2019,year==2018) %>% 
      pull(total) %>% 
      mean()
)
#### need other reports

```

## Problem 2
###
```{r}
pols_month_df<-read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon,into=c("year", "month", "day")) %>% 
  mutate(year=as.integer(year),month=as.integer(month),day=as.integer(day),) %>% 
  mutate(month=substr(month.name[month],1,3)) %>% 
  mutate(president=as.character(prez_gop)) %>% 
  mutate(president=recode(president,"1"="gop","0"="dem","2"="gop")) %>% 
  select(everything(),-day,-prez_gop,-prez_dem)

two_to_four <- function(x, year=1945){
  m <- x %% 100
  x <- ifelse(m > year %% 100, 1900+m, 2000+m)
}

snp_df<-read_csv("data/fivethirtyeight_datasets/snp.csv")%>% 
  janitor::clean_names() %>% 
  separate(date,into=c("month", "day", "year")) %>% 
  mutate(year=two_to_four(as.integer(year)),
         month=substr(month.name[as.integer(month)],1,3),
         day=as.integer(day),) %>% 
  arrange(year,month,day) %>% 
  relocate(year,month,day) %>% 
  select(-day)


### I have no clues why I cannot use read_csv, 
## it will create another kind of file
## unemployment_df<-read_csv("data/fivethirtyeight_datasets/unemployment.csv")
unemployment_df<-read.csv("data/fivethirtyeight_datasets/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec,
    names_to="month",
    values_to = "unemployment"
  ) %>% 
  janitor::clean_names()
combo_df<-
  left_join(snp_df,pols_month_df,by=c("year","month")) %>% 
  left_join(unemployment_df,by=c("year","month"))

##str(unemployment_df)
##unemployment_df$
## need more reports
```

### Brief Report
```{r report3}
##report_creator <- function(x,y){
##  x<-as.data.frame(x)
##  cat("The dimension of ",y,"is",dim(x),".The range of years is",
##        range(x$year),
##      ". The main variables' names are:
##",
##(x)
##)
##}
cat(
"The dimension of pols month is",dim(pols_month_df),".The range of years is",
pull(pols_month_df,year) %>% 
range(),".
The main variables' names are:
",
colnames(pols_month_df)
)

cat(
"The dimension of snp is",dim(snp_df),".The range of years is",
pull(snp_df,year) %>% 
range(),".
The main variables' names are:
",
colnames(snp_df)
)

cat(
"The dimension of unemployment is",dim(unemployment_df),".The range of years is",
pull(unemployment_df,year) %>% 
range(),".
The main variables' names are:
",
colnames(unemployment_df)
)


```

## Problem 3
###
```{r}
baby_names_df<-read_csv("data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(childs_first_name=str_to_lower(childs_first_name),
         gender=str_to_lower(gender),
         ethnicity=str_to_lower(ethnicity)) %>%
  mutate(ethnicity=recode(ethnicity,
                          "asian and pacific islander"="asian and paci",
                          "black non hispanic"="black non hisp",
                          "white non hispanic"="white non hisp")) %>% 
  distinct()

distinct(baby_names_df,ethnicity) %>% 
  pull(ethnicity)


Olivia<-filter(baby_names_df,gender=="female",childs_first_name=="olivia") %>%
  mutate(year=year_of_birth) %>% 
  select(-count,-year_of_birth) %>% 
  relocate(childs_first_name,year) %>% 
  knitr::kable()
Olivia

male_most_popular<-filter(baby_names_df,gender=="male",rank==1) %>% 
  mutate(year=year_of_birth) %>% 
  select(-count,-year_of_birth) %>% 
  relocate(childs_first_name,year) %>% 
  knitr::kable()
male_most_popular


male_nohis_2016_df<-filter(baby_names_df,
                           gender=="male",
                           year_of_birth==2016,
                           grepl("white non hisp",ethnicity)) %>% 
  select(rank,count)

plot<-ggplot(male_nohis_2016_df, aes(x=rank, y=count))+
  geom_point(shape=1,color="blue")
plot
ggsave("male_nohis_2016_df.png",plot)

```
